server:
  ##开启HTTPS
  port: 443
  ssl:
    ## SSL证书路径
    key-store: classpath:prod.pfx
    ##SSL证书密码
    key-store-password: wkhp58w00b1
    key-store-type: PKCS12

spring:
  datasource:
    url: ##psql地址
    username: ##账号
    password: ##密码
  data:
    redis:
      host: ##地址
      database: 5
      password: ##密码
      port: 6379

    mongodb:
      host: ##地址
      port: 27017
      database: ##数据库
      username: ##账号
      password: ##密码

  mail:
    host: ##smtp.163.com
    port: 465
    username: ##邮箱用户名
    password: ###密钥
    from: ##邮箱地址
    #    因为25端口被封闭,所以只能使用smtps,465端口进行发送邮件
    protocol: smtps

mybatis:
  configuration:
    #        ??????????
    map-underscore-to-camel-case: true
  #mapper?xml?????
  mapper-locations: classpath:mapper/*.xml
  ##不设置包,找不到那个user类,传入参数的选择,就是insert标签的parameterType
  type-aliases-package: edumindai.model.entity

  #
##讯飞api配置
#iflytek:
#  hostUrl: https://spark-api.xf-yun.com/v3.1/chat
#  apiKey: 0eed4b6468e4c5fb222b23ed6de3673e
#  apiSecret: YmUwY2IzMTkzMzBhYmRjYjM2ZThiMDIx
#  appid: f52d143b
#  domain: generalv3

#讯飞api配置3.5
iflytek:
  hostUrl: ##讯飞大模型请求地址
  apiKey: ##讯飞请求的密钥
  apiSecret: ##讯飞请求的密钥
  appid: ##讯飞请求的appid
  domain: ##请求模型

#minio的
oss:
  #  minio的地址
  endpoint: ##minio地址:http://example.com:9000
  access-key: ##minio AK
  secret-key: ##minio SK
  #  桶名
  bucket: ##桶名称
  #  文件地址的前缀
  prefix: ##地址/桶名


