spring:
  datasource:
    url: jdbc:postgresql://114.132.67.226:5432/edumindai
    username: root
    password: abC123456@
  profiles:
    active: dev

  data:
    redis:
      host: 114.132.67.226
      database: 5
      password: abC123456@
      port: 6379

    mongodb:
      host: 114.132.67.226
      port: 27017
      database: eduMindAI
      username: xiaolirw
      password: abC123456@

  mail:
    host: smtp.163.com
    port: 465
    username: ljz2020comeon@163.com
    password: QSWTCTJFMQRQEIIR
    from: ljz2020comeon@163.com
#    因为25端口被封闭,所以只能使用smtps,465端口进行发送邮件
    protocol: smtps

mybatis:
  configuration:
    #        ??????????
    map-underscore-to-camel-case: true
  #mapper?xml?????
  mapper-locations: classpath:mapper/*.xml

  ##不设置包,找不到那个user类,传入参数的选择,就是insert标签的parameterType
  type-aliases-package: edumindai.model.entity

#讯飞api配置
iflytek:
  hostUrl: https://spark-api.xf-yun.com/v3.1/chat
  apiKey: 0eed4b6468e4c5fb222b23ed6de3673e
  apiSecret: YmUwY2IzMTkzMzBhYmRjYjM2ZThiMDIx
  appid: f52d143b

#minio的
oss:
  #  minio的地址
  endpoint: http://114.132.67.226:9000
  access-key: minio
  secret-key: minio123
  #  桶名
  bucket: xiaoxin
  #  文件地址的前缀
  prefix: 114.132.67.226:9000/xiaoxin




